main: me.mrletsplay.mrcore.bukkitimpl.MrCorePlugin
name: MrCore_BukkitImpl
version: "2.3.34"
api-version: "1.13"
author: MrLetsplay2003

commands:
  mrcore:
  mrcoreui:
  mrcorelegacyui:
  mrcoredebug: