main: me.mrletsplay.mrcore.bukkitimpl.MrCorePlugin
name: MrCore_BukkitImpl
version: "${project.version}"
api-version: "1.13"
author: "MrLetsplay2003"
load: "STARTUP"

commands:
  mrcore:
  mrcoreui:
  mrcorelegacyui:
  mrcoredebug: