package me.mrletsplay.mrcore.mysql.protocol.flag;

public class MySQLStatusFlag {

	public static final int
		SERVER_STATUS_IN_TRANS = 0x1,
		SERVER_STATUS_AUTOCOMMIT = 0x2,
		SERVER_MORE_RESULTS_EXISTS = 0x8,
		SERVER_STATUS_NO_GOOD_INDEX_USED = 0x10,
		SERVER_STATUS_NO_INDEX_USED = 0x20,
		SERVER_STATUS_CURSOR_EXISTS = 0x40,
		SERVER_STATUS_LAST_ROW_SENT = 0x80,
		SERVER_STATUS_DB_DROPPED = 0x100,
		SERVER_STATUS_NO_BACKSLASH_ESCAPES = 0x200,
		SERVER_STATUS_METADATA_CHANGED = 0x400,
		SERVER_QUERY_WAS_SLOW = 0x800,
		SERVER_PS_OUT_PARAMS = 0x1000,
		SERVER_STATUS_IN_TRANS_READONLY = 0x2000,
		SERVER_SESSION_STATE_CHANGED = 0x4000;
	
}
